import { createServer } from 'node:http';
createServer((request, response) => {
  const url = new URL(request.url, 'http://127.0.0.1:3207');
  const fixed = url.searchParams.has('fixed');
  const kind = url.pathname.slice(1);
  response.setHeader('Content-Type', 'text/html');
  response.end(`<!doctype html><meta charset="utf-8"><link rel="icon" href="data:,"><style>
  *{box-sizing:border-box}body{margin:0;background:#f3f5f7;color:#253347;font:18px system-ui}header{height:72px;background:white;border-bottom:1px solid #dae1e8;padding:24px 44px;font-weight:600}main{margin:56px 64px}h1{font-size:30px;margin-bottom:12px}p{color:#627186}button{font:inherit;background:white;border:1px solid #b7c6d3;padding:10px 20px;border-radius:6px;cursor:pointer}nav{position:relative;display:flex;gap:12px;margin:30px 0}#sub{position:absolute;left:0;top:52px;z-index:2;box-shadow:0 5px 16px #17233022}#choose{position:absolute;left:166px;top:78px;z-index:3;box-shadow:0 5px 16px #17233022}#reference{width:420px;border-left:1px solid #60758a;padding:16px;margin:24px 0}#target{width:420px;padding:24px;background:white;border:1px solid #c2ced9;border-radius:6px}#status{margin-top:28px;color:#345d49}#flash{height:170px;background:#dcefe4;padding:24px;border-radius:6px}small{font-size:13px;color:#627186}</style>
  <header>ShopLite <small> / QA workspace</small></header><main><h1>${kind === 'menu' ? 'Workspace preferences' : kind === 'geometry' ? 'Invoice summary' : 'Loading state'}</h1><p>Review the application behavior after the recorded action.</p>
  ${kind === 'menu' ? '<nav><button id="nav">Workspace</button><button id="sub" hidden>Preferences</button><button id="choose" hidden>Notifications</button></nav><div id="target">Notifications: Enabled</div>' : kind === 'geometry' ? '<button id="load">Refresh invoice</button><div id="reference">Reference edge</div><div id="target">Invoice total<br><strong>$128.00</strong></div>' : '<button id="load">Load account</button><div id="target"><div id="flash">Account details remain visible</div></div>'}
  <div id="status">Ready</div></main><script>
  const fixed=${fixed}; window.hadFlash=false;
  const target=document.querySelector('#target'),status=document.querySelector('#status');
  ${kind === 'menu' ? `document.querySelector('#nav').onclick=()=>document.querySelector('#sub').hidden=false;document.querySelector('#sub').onclick=()=>document.querySelector('#choose').hidden=false;document.querySelector('#choose').onclick=()=>{document.querySelector('#sub').hidden=true;document.querySelector('#choose').hidden=true;target.textContent=fixed?'Notifications: Disabled':'Notifications: Enabled';status.textContent='Preference saved';console.info('Notification update completed')}` : kind === 'geometry' ? `document.querySelector('#load').onclick=()=>{target.style.marginLeft=fixed?'0px':'12px';status.textContent='Invoice refreshed';console.info('Invoice refresh completed')}` : `document.querySelector('#load').onclick=()=>{status.textContent='Loading';console.info('Account request started');const start=performance.now();function draw(now){if(now-start<300){status.textContent='Loading '+Math.round((now-start)/3)+'%';if(!fixed){window.hadFlash=true;document.querySelector('#flash').style.background='#ffc7bd';document.querySelector('#flash').textContent='Account details disappeared'}requestAnimationFrame(draw)}else{document.querySelector('#flash').style.background='#dcefe4';document.querySelector('#flash').textContent='Account details remain visible';status.textContent='Account loaded';console.info('Account request completed')}}requestAnimationFrame(draw)}`}
  </script>`);
}).listen(3207, '127.0.0.1');
