#!/usr/bin/env node
/**
 * Compile overlay-theme.tokens.json into:
 *  1. packages/viewer/tokens/tokens.json + CSS custom properties
 *  2. a typed TS module for diagnostic planning
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokensPath = join(root, 'tokens/overlay-theme.tokens.json');
const theme = JSON.parse(readFileSync(tokensPath, 'utf8'));

const outDir = join(root, 'dist/generated');
mkdirSync(outDir, { recursive: true });

const ts = `/* AUTO-GENERATED by scripts/build-tokens.mjs — do not edit */
export const overlayTheme = ${JSON.stringify(theme, null, 2)} as const;

export type OverlayTheme = typeof overlayTheme;
export type OverlayColorName = keyof typeof overlayTheme.colors;

export function severityColor(
  severity: keyof typeof overlayTheme.severityMap,
): string {
  const token = overlayTheme.severityMap[severity];
  return overlayTheme.colors[token].hex;
}
`;

const sourcePath = join(root, 'src/generated/overlay-theme.ts');
if (process.argv.includes('--write-source')) writeFileSync(sourcePath, ts);
else if (readFileSync(sourcePath, 'utf8') !== ts)
  throw new Error(
    'Generated theme source drift: run build-tokens.mjs --write-source and review the change',
  );

const cssLines = [
  '/* AUTO-GENERATED by @jitterbox/repro-contracts scripts/build-tokens.mjs */',
  ':root {',
];
for (const [name, entry] of Object.entries(theme.colors)) {
  const cssName = name.startsWith('repro-') ? name : `repro-${name}`;
  cssLines.push(`  --${cssName}: ${entry.hex};`);
}
cssLines.push(`  --repro-inset: ${String(theme.safeZones.inset)}px;`);
cssLines.push(
  `  --repro-bottom-band: ${String(theme.safeZones.bottomBand)}px;`,
);
cssLines.push('}');
cssLines.push('');

const viewerTokensDir = join(root, 'dist/tokens');
mkdirSync(viewerTokensDir, { recursive: true });
writeFileSync(
  join(viewerTokensDir, 'tokens.json'),
  `${JSON.stringify(theme, null, 2)}\n`,
);
writeFileSync(join(viewerTokensDir, 'overlay-theme.css'), cssLines.join('\n'));

const generatedCss = join(outDir, 'overlay-theme.css');
writeFileSync(generatedCss, cssLines.join('\n'));

console.log('Wrote generated theme TS, CSS, and viewer tokens.');
