#!/usr/bin/env node
/**
 * Compile overlay-theme.tokens.json into:
 *  1. regenerated ASS colours (never hand-write)
 *  2. packages/viewer/tokens/tokens.json + CSS custom properties
 *  3. a typed TS module for render/compositor
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const repoRoot = join(root, '../..');
const tokensPath = join(root, 'tokens/overlay-theme.tokens.json');
const theme = JSON.parse(readFileSync(tokensPath, 'utf8'));

/** @param {string} hex */
export function hexToAss(hex) {
  const h = hex.replace('#', '');
  if (h.length !== 6 && h.length !== 8) {
    throw new Error(`Invalid hex colour: ${hex}`);
  }
  const r = h.slice(0, 2).toUpperCase();
  const g = h.slice(2, 4).toUpperCase();
  const b = h.slice(4, 6).toUpperCase();
  const a = h.length === 8 ? h.slice(6, 8) : 'FF';
  const invertedA = (255 - Number.parseInt(a, 16))
    .toString(16)
    .padStart(2, '0')
    .toUpperCase();
  return `&H${invertedA}${b}${g}${r}`;
}

let assDrift = 0;
for (const [name, entry] of Object.entries(theme.colors)) {
  const generated = hexToAss(entry.hex);
  if (entry.ass !== generated) {
    console.warn(
      `ASS drift for ${name}: token=${entry.ass} generated=${generated}`,
    );
    entry.ass = generated;
    assDrift += 1;
  }
}

if (assDrift > 0) {
  writeFileSync(tokensPath, `${JSON.stringify(theme, null, 2)}\n`);
  console.log(`Rewrote ${String(assDrift)} ASS colour(s) in tokens.`);
}

const outDir = join(root, 'src/generated');
mkdirSync(outDir, { recursive: true });

const ts = `/* AUTO-GENERATED by scripts/build-tokens.mjs — do not edit */
export const overlayTheme = ${JSON.stringify(theme, null, 2)} as const;

export type OverlayTheme = typeof overlayTheme;
export type OverlayColorName = keyof typeof overlayTheme.colors;

export function hexToAss(hex: string): string {
  const h = hex.replace('#', '');
  if (h.length !== 6 && h.length !== 8) {
    throw new Error(\`Invalid hex colour: \${hex}\`);
  }
  const r = h.slice(0, 2).toUpperCase();
  const g = h.slice(2, 4).toUpperCase();
  const b = h.slice(4, 6).toUpperCase();
  const a = h.length === 8 ? h.slice(6, 8) : 'FF';
  const invertedA = (255 - Number.parseInt(a, 16))
    .toString(16)
    .padStart(2, '0')
    .toUpperCase();
  return \`&H\${invertedA}\${b}\${g}\${r}\`;
}

export function severityColor(
  severity: keyof typeof overlayTheme.severityMap,
): string {
  const token = overlayTheme.severityMap[severity];
  return overlayTheme.colors[token].hex;
}

export function severityAss(
  severity: keyof typeof overlayTheme.severityMap,
): string {
  const token = overlayTheme.severityMap[severity];
  return overlayTheme.colors[token].ass;
}
`;

writeFileSync(join(outDir, 'overlay-theme.ts'), ts);

const cssLines = [
  '/* AUTO-GENERATED by @repro/contracts scripts/build-tokens.mjs */',
  ':root {',
];
for (const [name, entry] of Object.entries(theme.colors)) {
  const cssName = name.startsWith('repro-') ? name : `repro-${name}`;
  cssLines.push(`  --${cssName}: ${entry.hex};`);
}
cssLines.push(`  --repro-inset: ${String(theme.safeZones.inset)}px;`);
cssLines.push(
  `  --repro-bottom-band: ${String(theme.safeZones.bottomBand)}px;`,
);
cssLines.push('}');
cssLines.push('');

const viewerTokensDir = join(repoRoot, 'packages/viewer/tokens');
mkdirSync(viewerTokensDir, { recursive: true });
writeFileSync(
  join(viewerTokensDir, 'tokens.json'),
  `${JSON.stringify(theme, null, 2)}\n`,
);
writeFileSync(join(viewerTokensDir, 'overlay-theme.css'), cssLines.join('\n'));

const generatedCss = join(outDir, 'overlay-theme.css');
writeFileSync(generatedCss, cssLines.join('\n'));

console.log('Wrote generated theme TS, CSS, and viewer tokens.');
