import { z } from 'zod';
export const annotationComponentSchema = z.enum([
  'target-ring',
  'leader',
  'plate',
  'callout',
  'step-badge',
  'progress-rail',
  'chapter',
  'console-toast',
  'pause-badge',
  'speed-chip',
  'click-ripple',
  'cursor-path',
  'keystroke-pill',
  'layout-shift-pair',
  'hit-target-guide',
  'hidden-ghost',
  'stacking-labels',
  'roi-magnifier',
  'freeze-banner',
  'vitals-hud',
  'redaction',
  'outcome-pair',
  'slate',
  'delta-caption',
]);
