import { z } from 'zod';
export const capabilitySchema = z.object({
  id: z.string(),
  surface: z.enum(['cli', 'playwright', 'mcp']),
  title: z.string(),
  status: z.enum(['implemented', 'unsupported', 'unavailable']),
  invocation: z.string(),
  description: z.string(),
  inputs: z.array(z.string()),
  outputs: z.array(z.string()),
  prerequisites: z.array(z.string()),
  timingEffects: z.string(),
  privacy: z.string(),
  failureModes: z.array(z.string()),
  verification: z.string(),
  example: z.string(),
});
export type Capability = z.infer<typeof capabilitySchema>;
const entries: [string, string, string, string, string[], string[], string][] =
  [
    [
      'migrate-run',
      'Migrate a run manifest explicitly',
      'repro migrate-run older-run --out-dir migrated-run',
      'Copy verified artifacts and preserve the original run manifest while materializing current schema defaults. Missing source identity, observations and proof remain unknown. Legacy delivery-only manifests stay on their compatibility commands and require recapture for committed evidence.',
      ['Existing run directory', 'New output directory'],
      [
        'Migrated run manifest',
        'Original manifest archive',
        'Verified local artifacts',
      ],
      'Verify artifact hashes and preserved outcomes. Missing or corrupt assets must reject migration; unknown source identity must still block verified paired export.',
    ],
    [
      'render',
      'Render a run presentation',
      'repro render run',
      'Render titles, steps, measured highlights and reading holds from a committed evidence run. Checkpoint highlights select up to three measured targets with short descriptive callout labels; [] suppresses outlines. Labels are placed outside measured targets and presentation chrome. Missing or ambiguous geometry and unplaceable callouts fail explicitly. Use --evidence edited.json for presentation-only revisions without recapture.',
      [
        'run directory',
        'optional --evidence edited.json with checkpoint highlights: [{target, label}]',
      ],
      ['annotated video', 'annotated stills', 'captions'],
      'Inspect titles, steps and outlines in actual output pixels.',
    ],
    [
      'export',
      'Export audited presentation',
      'repro export run --out-dir bundle',
      'Package complete presentation evidence after a real-frame privacy audit.',
      ['complete run'],
      ['portable viewer bundle'],
      'Missing OCR and incomplete evidence must block export.',
    ],
    [
      'doctor',
      'Inspect dependencies',
      'repro doctor',
      'Check local browser, FFmpeg/FFprobe, required filters, fonts, OCR and capture backend.',
      ['local installation'],
      ['dependency statuses'],
      'Remove OCR and verify strict export is unavailable.',
    ],
    [
      'capabilities',
      'Discover capabilities',
      'repro capabilities --json',
      'List supported operations and limitations.',
      [],
      ['capability registry'],
      'Every implemented invocation is registered by the CLI.',
    ],
    [
      'describe',
      'Read capability guidance',
      'repro describe frame --json',
      'Read inputs, examples, timing, privacy and verification before acting.',
      ['capability ID'],
      ['capability descriptor'],
      'Unknown IDs fail with invalid-input.',
    ],
    [
      'recipes',
      'Choose an evidence recipe',
      'repro recipes --json',
      'Choose a committed specification for the claim.',
      [],
      ['recipes'],
      'Validate each recipe with validate-evidence.',
    ],
    [
      'validate-evidence',
      'Validate evidence semantics',
      'repro validate-evidence evidence.json',
      'Validate structure, references, titles, steps and trigger.',
      ['evidence specification'],
      ['validation result'],
      'Reject unresolved targets and missing trigger.',
    ],
    [
      'init',
      'Create a scenario',
      'repro init',
      'Create an editable Checkout example, evidence spec and capture config. This is a starting example, not automatic bug understanding. During discovery, read the bug and acceptance criteria; distinguish reported behavior from measured facts; choose interaction, geometry or transient recipe; replace fixture titles, meaningful steps, trigger, targets and designated outcome checks. Bind locators from the actual application. Choose checkpoint highlights for the intended control and decisive result, using descriptive labels rather than unverified causes. Commit both files, run, inspect actual pixels, then verify before exporting.',
      [],
      ['committed input files'],
      'Run generated scenario against a supplied URL.',
    ],
    [
      'run',
      'Execute committed evidence',
      'repro run scenario.spec.ts --url http://localhost:3000 --evidence evidence.json',
      'Execute public Playwright tests in an isolated context; record every attempt. --watch coalesces changes and cancels superseded runs. --watch-server server.json owns one persistent build/server process with command, args, optional cwd, loopback readiness url and optional startupTimeoutMs; configure Playwright webServer.reuseExistingServer=true. Server shutdown is independent of per-run browser cancellation.',
      ['Playwright spec', 'evidence spec', 'URL'],
      ['run manifest', 'checkpoints', 'normalized recording'],
      'Inspect required checkpoints and designated before/after outcome.',
    ],
    [
      'frame',
      'Inspect an evidence frame',
      'repro frame run --checkpoint result',
      'Select a checkpoint PNG or recording frame with actual timing and uncertainty. For brief states, declare a transient checkpoint.frame with a segment, event kind/match/occurrence, offsetMs and maxOffsetMs; wrap the triggering interval in repro.segment and inspect the selected PNG after the run. No new screenshot or stability wait is inserted. Crops retain the context and report requested CSS bounds, actual pixel bounds, pixel scale and the resulting CSS transform; fractional edges round outward.',
      ['run directory', 'checkpoint or timestamp'],
      [
        'context image',
        'optional crop',
        'actualMs, requestedMs, selectionOffsetMs, uncertaintyMs and eventSelection',
        'requestedCrop, cropTransform, pixelTransform and pixelScale',
      ],
      'Compare returned crop pixels against the context using pixelTransform; never assume requested fractional bounds equal integer pixel bounds.',
    ],
    [
      'review',
      'Review local proof',
      'repro review after-run --baseline before-run',
      'Serve local evidence on loopback with actual recording durations, screenshot acquisition uncertainty, passive browser console/request diagnostics, proof segments, and unmatched or low-confidence alignment. Unique decoded-image fallback matches are labeled estimates and never count as semantic proof. Uncertain comparisons default to original timing; synchronized inspection can be selected explicitly.',
      ['run directory', 'optional explicit baseline run directory'],
      ['loopback viewer'],
      'Inspect title, steps, outcomes, context and alignment warnings before export. Review does not turn an unverified comparison into successful proof.',
    ],
    [
      'record',
      'Record durable locators',
      'repro record http://localhost:3000',
      'Wrap upstream Playwright codegen for an editable committed spec.',
      ['URL'],
      ['Playwright spec'],
      'Review assertions and locators before deterministic execution.',
    ],
    [
      'capture',
      'Capture browser pixels',
      'repro capture --config repro.config.json --url http://localhost:3000',
      'Low-level capture adapter. Prefer run for semantic evidence.',
      ['config', 'URL'],
      ['raw local capture'],
      'Verify timestamps and complete frame tables; raw media is private.',
    ],
    [
      'annotate',
      'Render presentation',
      'repro annotate --config repro.config.json --events run/events.jsonl --video run/capture.mp4 --out-dir output',
      'Render a deterministic timeline without another application run.',
      ['events', 'recording', 'config'],
      ['annotated MP4', 'captions'],
      'Inspect highlights and reading holds in output pixels.',
    ],
    [
      'compare',
      'Compare before and after',
      'repro compare before-run-directory after-run-directory',
      'Compare controlled runs and reject incompatible environments.',
      [
        'before run directory',
        'after run directory; legacy JSON manifests supported by adapter',
      ],
      ['comparison report'],
      'Check measured observations and unmatched checkpoints.',
    ],
    [
      'render-compare',
      'Render comparison',
      'repro render-compare --composition after-run/comparison.json --video-a before.mp4 --video-b after.mp4 --out-dir output',
      'Render a compare report or legacy composition using every measured synchronization knot. Legacy inputs with fewer than two knots use explicitly reported original timing. Synchronized outputTiming reports the measured endpoint, encoded duration and up to one added terminal frame so the final cue is visible without advancing its timestamp. Pane a must be Before and pane b After; all source and output knot times must increase. ROI requires measured shared bounds; blink requires explicit opt-in.',
      [
        'comparison report or composition',
        'normalized before and after videos',
      ],
      ['comparison MP4', 'outputTiming for synchronized media'],
      'Measure checkpoint alignment within two output frames.',
    ],
    [
      'quality',
      'Evaluate evidence',
      'repro quality --input metrics.json',
      'Low-level report gate; supplied metrics are not independent capture proof.',
      ['metrics'],
      ['quality report'],
      'Use measured decoded pixels; synthetic metrics must be labelled.',
    ],
    [
      'validate-config',
      'Validate capture configuration',
      'repro validate-config --config repro.config.json',
      'Validate semantic feature conflicts.',
      ['config'],
      ['validation result'],
      'Reject compare without controlled and unsupported OS capture.',
    ],
    [
      'package',
      'Package evidence',
      'repro package --out-dir bundle --asset mp4:proof.mp4',
      'Portable viewer packaging; export requires artifact audit.',
      ['audited assets'],
      ['viewer bundle'],
      'Relocate bundle, recheck hashes and keyboard navigation.',
    ],
    [
      'file',
      'Deliver evidence',
      'repro file --system jira --evidence proof.mp4 --title "Checkout proof"',
      'Audit and deliver evidence through configured ALM.',
      ['audited evidence', 'ALM configuration'],
      ['delivery result'],
      'Verify remote upload and idempotent retry.',
    ],
  ];
export const capabilities: Capability[] = entries.map(
  ([id, title, invocation, description, inputs, outputs, verification]) => ({
    id,
    title,
    invocation,
    description,
    inputs,
    outputs,
    verification,
    status: 'implemented',
    surface: 'cli',
    prerequisites: [
      'run',
      'capture',
      'annotate',
      'render-compare',
      'frame',
    ].includes(id)
      ? ['Chromium installed', 'FFmpeg installed']
      : [],
    timingEffects: ['run', 'capture'].includes(id)
      ? 'Controlled profile fixes Date and RNG and reduces motion. Faithful leaves timing and network unchanged. Screenshots occupy a measured capture interval.'
      : 'No application timing changes. Presentation holds must retain a separate execution timeline.',
    privacy:
      'Keep raw captures and diagnostics local. Strict export requires actual frame OCR and content-bound audit. Never include credentials in prompts.',
    failureModes: [
      'Invalid or missing inputs',
      'Required evidence unavailable',
      'Dependency unavailable',
    ],
    example: invocation,
  }),
);
capabilities.push({
  id: 'os-capture',
  surface: 'cli',
  title: 'Operating-system capture',
  status: 'unsupported',
  invocation: 'none',
  description:
    'No OS capture backend is implemented. Page capture cannot prove browser chrome or native dialogs.',
  inputs: [],
  outputs: [],
  prerequisites: [],
  timingEffects: 'Unavailable',
  privacy: 'Unavailable',
  failureModes: ['unsupported-backend'],
  verification: 'OS configuration must fail without fallback.',
  example: 'repro doctor',
});
export function describeCapability(id: string) {
  const value = capabilities.find((c) => c.id === id);
  if (!value) throw new Error(`Unknown capability: ${id}`);
  return value;
}

const fixtureCapabilities = [
  [
    'check',
    'Verify an ordinary checkpoint condition',
    "await repro.check('ready', 'Cart is loaded', () => expect(page.getByRole('heading')).toHaveText('Cart'))",
    'Record a named setup or state assertion before a stable checkpoint. Its failure is rethrown and makes the run unsuccessful even if caller code catches it. It never proves bug reproduction or fix verification; use outcome for the designated claim. A fourth Page argument selects a popup.',
    'Declare the checkpoint and record this check before its stable screenshot.',
    'Verify successful checks satisfy checkpoint evidence, failed checks block successful export, and only designated outcomes produce verified outcome labels.',
  ],
  [
    'target',
    'Bind a named target',
    "repro.target('target', page.getByRole('button', {name:'Checkout',exact:true}))",
    'Bind an evidence target ID to a durable Playwright locator. Geometry is measured at capture time, never inferred from a selector.',
    'Declare the ID in evidence.targets.',
    'Missing or ambiguous targets remain explicit failures.',
  ],
  [
    'step',
    'Record a meaningful step',
    "await repro.step('trigger', async () => { await page.getByRole('button', {name:'Checkout'}).click(); })",
    'Record a semantic step independently of visual badge settings. Use descriptive titles and explicit trigger identification in the committed specification.',
    'Declare the step ID and descriptive title in evidence.steps.',
    'Every required step must be present, numbered and meaningful.',
  ],
  [
    'checkpoint',
    'Capture checkpoint context',
    "await repro.checkpoint('result')",
    'Capture context PNG and measured target geometry after a specific assertion. No implicit stability or network-idle wait is added. A second Page argument selects a popup.',
    'Declare checkpoint ID, requirements and named targets.',
    'Inspect actual pixels, timestamp interval, target bounds and crop transform.',
  ],
  [
    'segment',
    'Record a named proof interval',
    "await repro.segment('loading', async () => { await page.getByRole('button', {name:'Load'}).click(); await expect(page.getByText('Loaded')).toBeVisible(); })",
    'Declare segments with id, title, step and required in evidence.json, then wrap the trigger and observation interval inside its declared repro.step. Capture is already running before the action. No stability wait or timing change is injected. Required missing or failed segments block evidence completion.',
    'A declared segment and an active matching semantic step; call before the trigger. Optional Page argument scopes popup evidence.',
    'Inspect run.segments, start/end times, captured frames and the actual outcome. Use committed transient checkpoint.frame selection to extract event-linked pixels afterward.',
  ],
  [
    'outcome',
    'Designate the proof assertion',
    "await repro.outcome('result', () => expect(page.getByRole('heading')).toHaveText('Checkout'))",
    'Record an executed Playwright assertion. A before mismatch may prove reproduction; after must pass. Setup, browser and unrelated code errors are not proof. Pass a third Page argument for a popup assertion.',
    'Use expect from @repro/playwright and a declared checkpoint.',
    'Check assertionPassed false before and true after; inspect the resulting state.',
  ],
  [
    'hit-test',
    'Sample an invisible obstruction',
    "await repro.hitTest('result', 'target', {x:170,y:110})",
    'Record measured bounds, sampled viewport CSS coordinates, hit-test stack and relevant styles. Calibrated pointer-down dispatch paths later in the same step/page are attached separately with event references and actual coordinates. A bracketed pre-action PNG and repeated geometry/style samples establish whether the outline aligns with that image. Changed geometry suppresses the outline. This adds screenshot acquisition time before the attempted interaction; use transient event frames for timing-sensitive behavior. A sample is not an entire hidden hitbox. No CSS modification or forced click is performed.',
    'Bind one unambiguous target and sample inside a semantic step before its natural interaction. Ancestor-frame interception is currently unsupported.',
    'Inspect eventCorrelation and compare actual coordinates/dispatch recipients with the sample and designated outcome. Missing or ambiguous correlation remains unavailable; do not infer a recipient from the hit-test stack.',
  ],
  [
    'visibility',
    'Observe target appearance or disappearance',
    "await repro.visibility('result', 'target')",
    'Sample attached/visible state without waiting or interacting. Records absent and hidden states explicitly; ambiguity or mutation during sampling is unsupported. Consecutive successful samples reference the prior observation and report appeared/disappeared/unchanged. Playwright visibility does not establish perceptibility or lack of occlusion.',
    'Bind the named target and list it in checkpoint.targets; require visibility in checkpoint.observations when needed.',
    'Inspect before/after samples and their timestamps. Use a separate assertion and screenshot for the claimed application outcome.',
  ],
  [
    'network',
    'Observe a response at a checkpoint',
    "const pending = page.waitForResponse('**/checkout'); await page.getByRole('button', {name:'Checkout'}).click(); await repro.network('result', await pending)",
    'Record a real Playwright Response with method, sanitized URL and HTTP status. Register the response wait before its trigger. No extra request is sent; headers and bodies are excluded. A measured HTTP error satisfies observation availability but does not establish outcome success. Transport failures remain in passive diagnostics.',
    'A declared checkpoint and a Response from the captured browser context.',
    'Assert the expected status and resulting UI separately; inspect the recorded response and passive failure events. Observation time is not response arrival time and temporal association is not causality.',
  ],
  [
    'accessibility',
    'Scan checkpoint accessibility',
    "await repro.accessibility('result')",
    'Run Axe at a declared checkpoint and record violation counts and rules. An accessibility scan does not replace the scenario outcome assertion.',
    'Chromium and @axe-core/playwright.',
    'Inspect recorded violations and designated outcome separately.',
  ],
  [
    'ready',
    'Await popup capture ownership',
    'await repro.ready(popup)',
    'Wait for page registration and an initial captured frame before acting on a new page.',
    'A Page in the scenario browser context.',
    'No editorial cut or action may depend on an uncaptured popup.',
  ],
] as const;
for (const [
  id,
  title,
  invocation,
  description,
  prerequisite,
  verification,
] of fixtureCapabilities)
  capabilities.push({
    id,
    surface: 'playwright',
    title,
    status: 'implemented',
    invocation,
    description,
    inputs: ['Committed evidence specification', 'Public Playwright fixture'],
    outputs: ['Run observations and inspectable artifacts'],
    prerequisites: [prerequisite],
    timingEffects:
      'Observation and screenshot acquisition take measured time; no artificial stability wait is inserted.',
    privacy:
      'Raw observations stay local. Strict export audits pixels and excludes raw diagnostics.',
    failureModes: [
      'Unknown ID',
      'Missing or ambiguous target',
      'Incomplete capture',
      'Unsupported frame boundary',
    ],
    verification,
    example: invocation,
  });
capabilities.push({
  id: 'experiment-native',
  surface: 'cli',
  title: 'Evaluate native screencast',
  status: 'implemented',
  invocation: 'repro experiment-native --out-dir experiment',
  description:
    'Run identical CDP/native capture experiments with tracing. Production retains CDP until all promotion gates pass.',
  inputs: ['Output directory'],
  outputs: ['Experiment report and local captures'],
  prerequisites: ['Pinned Chromium'],
  timingEffects: 'Runs isolated test contexts with deliberate fixture waits.',
  privacy: 'Experiment captures stay local.',
  failureModes: ['Capture dimensions or timestamps rejected'],
  verification:
    'Read promotion decision and every failed gate; never infer native support from API availability.',
  example: 'repro experiment-native --out-dir experiment',
});
capabilities.push({
  id: 'status',
  surface: 'mcp',
  title: 'Verify a run manifest',
  status: 'implemented',
  invocation: 'status({run:"/absolute/run-directory"})',
  description:
    'Verify every artifact hash and return full run provenance on demand.',
  inputs: ['Run directory'],
  outputs: ['Verified run manifest'],
  prerequisites: ['Repro stdio MCP server'],
  timingEffects: 'Reads artifacts without recapture.',
  privacy:
    'Full provenance remains local and can be verbose; use run summaries for ordinary discovery.',
  failureModes: ['Deleted or corrupt artifact'],
  verification: 'Corrupt a referenced artifact and verify status fails.',
  example: 'status({run:"/absolute/run-directory"})',
});
