import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const entry = resolve(root, 'src/probe-source.ts');
const distFile = resolve(root, 'dist/probe.iife.js');
const iifeModule = resolve(root, 'src/iife.ts');

await mkdir(resolve(root, 'dist'), { recursive: true });

await build({
  bundle: true,
  entryPoints: [entry],
  format: 'iife',
  legalComments: 'none',
  logLevel: 'info',
  outfile: distFile,
  platform: 'browser',
  sourcemap: false,
  target: 'es2022',
  treeShaking: true,
});

const source = await readFile(distFile, 'utf8');
const chunks = chunkString(source, 48).map((chunk) => `  ${quote(chunk)},`);
const generated = [
  '// Generated by scripts/build-iife.mjs.',
  'const chunks = [',
  ...chunks,
  '] as const;',
  '',
  "export const PROBE_IIFE = chunks.join('');",
  '',
].join('\n');

await writeFile(iifeModule, generated);

function chunkString(value, size) {
  const chunks = [];

  for (let index = 0; index < value.length; index += size) {
    chunks.push(value.slice(index, index + size));
  }

  return chunks;
}

function quote(value) {
  return JSON.stringify(value);
}
