/** Local review shares the scene's occurrence map. Text uses textContent exclusively. */
export function sceneReviewHtml(serialized: string) {
  return `<!doctype html><meta charset="utf-8"><title>Repro evidence review</title><style>body{background:#101721;color:#edf3f8;font:16px system-ui;margin:24px}video{width:100%;max-height:70vh}button,select{background:#24364a;color:#edf3f8;border:1px solid #52667b;border-radius:6px;padding:8px;margin-right:8px}main{display:grid;grid-template-columns:1fr 1fr;gap:16px}section{background:#1c2734;padding:16px;border-radius:8px;max-height:380px;overflow:auto}pre{white-space:pre-wrap;font-size:13px}h2{font-size:18px}button.event{display:block;width:100%;text-align:left;font:13px monospace;margin:6px 0}.track{height:3px;background:#70d4c3;margin-top:5px}#clock{margin:16px 0;color:#9ed9e7}</style><h1>Synchronized evidence review</h1><video controls src="proof.mp4"></video><div id="clock"></div><button id="previous">Previous frame</button><button id="next">Next frame</button><label>Event occurrence <select id="occurrences"></select></label><main><section><h2>Console and exceptions</h2><div id="console"></div></section><section><h2>Network lifecycle</h2><div id="network"></div></section><section><h2>Application state and vitals</h2><div id="state"></div></section><section><h2>Capture coverage</h2><pre id="coverage"></pre></section><section><h2>Checkpoint geometry and DOM observations</h2><pre id="observations"></pre></section><section><h2>Source frame identity</h2><pre id="identity"></pre></section></main><script>
 const data=${serialized},v=document.querySelector('video'),occurrences=document.querySelector('#occurrences');
 function jump(event){const matches=data.frames.filter((f,i)=>f.sourceMs>=event.t_mono && (!i||data.frames[i-1].sourceMs<event.t_mono));occurrences.replaceChildren();for(const f of matches){const o=document.createElement('option');o.value=String(f.outputMs/1000);o.textContent='Output '+(f.outputMs/1000).toFixed(3)+'s';occurrences.append(o)}if(matches.length)v.currentTime=matches[0].outputMs/1000;}
 occurrences.onchange=()=>v.currentTime=Number(occurrences.value);document.querySelector('#previous').onclick=()=>v.currentTime=Math.max(0,v.currentTime-1/30);document.querySelector('#next').onclick=()=>v.currentTime+=1/30;
 function rows(id,events){const box=document.querySelector('#'+id);box.replaceChildren();for(const event of events.slice(-40)){const b=document.createElement('button');b.className='event';b.textContent=(event.t_mono/1000).toFixed(3)+'s · '+event.kind+' '+JSON.stringify(event.payload);b.onclick=()=>jump(event);box.append(b);if(id==='network'){const bar=document.createElement('div');bar.className='track';bar.style.width=Math.max(1,Math.min(100,event.t_mono/Math.max(1,data.frames.at(-1).sourceMs)*100))+'%';b.append(bar)}}}
 function update(){const f=data.frames[Math.min(data.frames.length-1,Math.floor(v.currentTime*30))];if(!f)return;document.querySelector('#clock').textContent='Output '+v.currentTime.toFixed(3)+'s · Source '+(f.sourceMs/1000).toFixed(3)+'s · '+f.segmentId;document.querySelector('#identity').textContent=JSON.stringify(f,null,2);const observed=data.events.filter(e=>e.t_mono<=f.sourceMs);rows('console',observed.filter(e=>/console|exception/.test(e.kind)));rows('network',observed.filter(e=>/network|transfer|request/.test(e.kind)));rows('state',observed.filter(e=>/scenario.state|vital|webmcp/.test(e.kind)));document.querySelector('#coverage').textContent=observed.filter(e=>e.kind==='diagnostic.coverage').map(e=>JSON.stringify(e.payload)).join('\n');document.querySelector('#observations').textContent=JSON.stringify((data.observations??[]).filter(o=>o.timeMs<=f.sourceMs).slice(-12),null,2)}v.addEventListener('timeupdate',update);v.addEventListener('seeked',update);update();</script>`;
}
